### PR TITLE
Add action to build and publish binaries on release

### PR DESCRIPTION
**Pull request by theothertomelliott**
This should allow easier use with Bazel.

### CODE REVIEW

**Comment by atavakoliyext** [comment]
Thanks @theothertomelliott 

Is there a way we can test builds of these binaries within this PR before merging?

**Comment by theothertomelliott** [comment]
I added the same change to a fork and generated this release: https://github.com/theothertomelliott/terraform-provider-teamcity/releases/tag/v0.3.0

You can see the actions run that generated the binaries at https://github.com/theothertomelliott/terraform-provider-teamcity/actions/runs/8040034794

**Comment by theothertomelliott** [comment]
Updated to prevent the node16 warnings: https://github.com/theothertomelliott/terraform-provider-teamcity/actions/runs/8040104530

**Review by bsaavedra17 — APPROVED** [review]
Looks good

**Pull request merged**
